
    insert into ingredient
        (id, name, test_data, unit_category)
    values
		(1, "butter", false, 1),
		(2, "cans condensed cream of chicken soup", false, 1),
		(3, "onion", false, 3),
		(4, "packages refrigerated biscuit dough", false, 1),
		(5, "cans condensed cream of mushroom soup", false, 1),
		(6, "package dry onion soup mix", false, 1),
		(7, "water", false, 1),
		(8, "pot roast", false, 2),
		(9, "packed brown sugar", false, 1),
		(10, "ketchup", false, 1),
		(11, "lean ground beef", false, 2),
		(12, "milk", false, 1),
		(13, "salt", false, 1),
		(14, "ground black pepper", false, 1),
		(15, "small onion", false, 3),
		(16, "ground ginger", false, 1),
		(17, "finely crushed saltine cracker crumbs", false, 1),
		(18, "white sugar", false, 1),
		(19, "vanilla extract", false, 1),
		(20, "all-purpose flour", false, 1),
		(21, "baking soda", false, 1),
		(22, "hot water", false, 1),
		(23, "semisweet chocolate chips", false, 1),
		(24, "chopped walnuts", false, 1),
		(25, "whole wheat rotini pasta", false, 1),
		(26, "fresh broccoli florets", false, 1),
		(27, "medium onion", false, 3),
		(28, "Cheddar cheese", false, 1),
		(29, "reduced-fat cream cheese", false, 1),
		(30, "fine dry Italian-seasoned bread crumbs", false, 1),
		(31, "brown sugar", false, 1),
		(32, "mashed overripe bananas", false, 1),
		(33, "pinch freshly grated nutmeg", false, 3),
		(34, "pinch cayenne pepper", false, 3),
		(35, "olive oil", false, 1),
		(36, "baby spinach leaves", false, 1),
		(37, "cold milk", false, 1),
		(38, "lemon zest", false, 1),
		(39, "boneless cod fillets", false, 2),
		(40, "lemon", false, 3),
		(41, "chopped fresh chives for garnish", false, 1),
		(42, "baking powder", false, 1),
		(43, "ground cinnamon", false, 1),
		(44, "vegetable oil", false, 1),
		(45, "grated zucchini", false, 1),
		(46, "chicken broth", false, 1),
		(47, "large egg", false, 3),
		(48, "soy sauce", false, 1),
		(49, "chile-garlic sauce ", false, 1),
		(50, "oyster sauce", false, 1),
		(51, "tamarind paste", false, 1),
		(52, "fish sauce", false, 1),
		(53, "palm sugar", false, 1),
		(54, "minced shallot", false, 1),
		(55, "minced fresh ginger root", false, 1),
		(56, "minced serrano pepper", false, 1),
		(57, "chopped fresh cilantro", false, 1),
		(58, "sliced green onion ", false, 1),
		(59, "can pumpkin puree", false, 1),
		(60, "ground nutmeg", false, 1),
		(61, "ground cloves", false, 1),
		(62, "unsalted butter", false, 1),
		(63, "egg", false, 3),
		(64, "egg yolk", false, 3),
		(65, "cauliflower florets", false, 2),
		(66, "mashed potato flakes", false, 1),
		(67, "low-fat milk", false, 1),
		(68, "margarine", false, 1),
		(69, "shredded reduced-fat Cheddar cheese", false, 1),
		(70, "thickly sliced bacon", false, 2),
		(71, "boneless lamb shoulder", false, 2),
		(72, "large onion", false, 3),
		(73, "beef stock", false, 1),
		(74, "diced carrots", false, 1),
		(75, "dried thyme", false, 1),
		(76, "white wine", false, 1),
		(77, "fresh blueberries", false, 1),
		(78, "Parmesan cheese", false, 1),
		(79, "mayonnaise", false, 1),
		(80, "fresh lemon juice", false, 1),
		(81, "dried basil", false, 1),
		(82, "onion powder", false, 1),
		(83, "celery salt", false, 1),
		(84, "tilapia fillets", false, 2),
		(85, "packages instant vanilla pudding mix", false, 1),
		(86, "chopped walnuts ", false, 1),
		(87, "sweet Italian sausage", false, 2),
		(88, "minced onion", false, 1),
		(89, "can crushed tomatoes", false, 1),
		(90, "cans tomato paste", false, 1),
		(91, "cans canned tomato sauce", false, 1),
		(92, "dried basil leaves", false, 1),
		(93, "fennel seeds", false, 1),
		(94, "Italian seasoning", false, 1),
		(95, "chopped fresh parsley", false, 1),
		(96, "lasagna noodles", false, 3),
		(97, "ricotta cheese", false, 1),
		(98, "mozzarella cheese", false, 2),
		(99, "grated Parmesan cheese", false, 1),
		(100, "unsweetened cocoa powder", false, 1),
		(101, "honey", false, 1),
		(102, "confectioners' sugar", false, 1),
		(103, "raisins", false, 1),
		(104, "caraway seeds", false, 1),
		(105, "buttermilk", false, 1),
		(106, "sour cream", false, 1),
		(107, "peeled and diced potatoes", false, 1),
		(108, "diced celery", false, 1),
		(109, "finely chopped onion", false, 1),
		(110, "diced cooked ham", false, 1),
		(111, "chicken bouillon granules", false, 1),
		(112, "ground white or black pepper", false, 1),
		(113, "skinless", false, 2),
		(114, "sliced carrots", false, 1),
		(115, "frozen green peas", false, 1),
		(116, "sliced celery", false, 1),
		(117, "chopped onion", false, 1),
		(118, "black pepper", false, 1),
		(119, "celery seed", false, 1),
		(120, "white vinegar", false, 1),
		(121, "packages fudge brownie mix ", false, 1),
		(122, "Irish cream liqueur ", false, 1),
		(123, "recipe pastry for a 9 inch double crust pie", false, 3),
		(124, "potatoes", false, 2),
		(125, "head cabbage", false, 3),
		(126, "bunch green onions", false, 3),
		(127, "half-and-half cream", false, 1),
		(128, "maple syrup", false, 1),
		(129, "balsamic syrup", false, 1),
		(130, "garlic powder", false, 1),
		(131, "pinch ground white pepper", false, 3),
		(132, "pinch ground nutmeg", false, 3),
		(133, "pinch ground dried chipotle pepper", false, 3),
		(134, "bottle barbeque sauce", false, 1),
		(135, "Italian salad dressing", false, 1),
		(136, "Worcestershire sauce", false, 1),
		(137, "paprika", false, 1),
		(138, "dry white wine", false, 1),
		(139, "cornstarch", false, 1),
		(140, "heavy whipping cream", false, 1),
		(141, "graham crackers", false, 3),
		(142, "packages cream cheese", false, 1),
		(143, "cold water", false, 1),
		(144, "cider vinegar", false, 1),
		(145, "clove garlic", false, 3),
		(146, "skinless chicken thighs", false, 3),
		(147, "lime", false, 3),
		(148, "diced onion", false, 1),
		(149, "minced garlic", false, 1),
		(150, "pinch ground cayenne pepper ", false, 3),
		(151, "ground beef chuck", false, 2),
		(152, "bulk Italian sausage", false, 2),
		(153, "cans chili beans", false, 1),
		(154, "can chili beans in spicy sauce", false, 1),
		(155, "cans diced tomatoes with juice", false, 1),
		(156, "can tomato paste", false, 1),
		(157, "large yellow onion", false, 3),
		(158, "green bell pepper", false, 3),
		(159, "red bell pepper", false, 3),
		(160, "bacon bits", false, 1),
		(161, "beer", false, 1),
		(162, "chili powder", false, 1),
		(163, "dried oregano", false, 1),
		(164, "ground cumin", false, 1),
		(165, "hot pepper sauce ", false, 1),
		(166, "cayenne pepper", false, 1),
		(167, "bag corn chips such as Fritos®", false, 1),
		(168, "package shredded Cheddar cheese", false, 1),
		(169, "seasoning salt", false, 1),
		(170, "Italian-style seasoned bread crumbs", false, 1),
		(171, "can condensed cream of mushroom soup", false, 1),
		(172, "can chili beans", false, 1),
		(173, "can black beans", false, 1),
		(174, "can whole kernel corn", false, 1),
		(175, "can tomato sauce", false, 1),
		(176, "can or bottle beer", false, 1),
		(177, "cans diced tomatoes with green chilies", false, 1),
		(178, "package taco seasoning", false, 1),
		(179, "package shredded Cheddar cheese ", false, 1),
		(180, "cornmeal", false, 1),
		(181, "dry ziti pasta", false, 2),
		(182, "jars spaghetti sauce", false, 1),
		(183, "provolone cheese", false, 1),
		(184, "molasses", false, 1),
		(185, "shortening", false, 1),
		(186, "cream of tartar", false, 1),
		(187, "crushed red pepper flakes", false, 1),
		(188, "sea salt", false, 1),
		(189, "chopped green bell pepper", false, 1),
		(190, "prepared yellow mustard", false, 1),
		(191, "degrees F/45 degrees C)", false, 3),
		(192, "bread flour", false, 1),
		(193, "bread machine yeast", false, 1),
		(194, "package cream cheese", false, 1),
		(195, "package devil's food cake mix", false, 1),
		(196, "package instant chocolate pudding mix", false, 1),
		(197, "warm water", false, 1),
		(198, "grated carrots", false, 1),
		(199, "chopped pecans", false, 1),
		(200, "cream cheese", false, 1),
		(201, "all-purpose apples", false, 1),
		(202, "quick-cooking oats", false, 1),
		(203, "active dry yeast", false, 1),
		(204, "inch slices", false, 3),
		(205, "shredded Cheddar cheese", false, 1),
		(206, "Italian-seasoned bread crumbs", false, 1),
		(207, "salmon fillets", false, 2),
		(208, "cans chunk chicken", false, 1),
		(209, "Ranch dressing", false, 1),
		(210, "pepper sauce ", false, 1),
		(211, "bunch celery", false, 3),
		(212, "box chicken-flavored crackers", false, 1),
		(213, "taco seasoning mix", false, 1),
		(214, "salsa", false, 1),
		(215, "sour cream ", false, 1),
		(216, "packed light brown sugar", false, 1),
		(217, "all-purpose flour for coating", false, 1),
		(218, "inch thick", false, 3),
		(219, "sliced mushrooms", false, 1),
		(220, "Marsala wine", false, 1),
		(221, "cooking sherry", false, 1),
		(222, "shredded", false, 2),
		(223, "can whole peeled tomatoes", false, 1),
		(224, "can enchilada sauce", false, 1),
		(225, "can chopped green chile peppers", false, 1),
		(226, "can chicken broth", false, 1),
		(227, "cumin", false, 1),
		(228, "bay leaf", false, 3),
		(229, "package frozen corn", false, 1),
		(230, "chopped cilantro", false, 1),
		(231, "uncooked white rice", false, 1),
		(232, "golden raisins", false, 1),
		(233, "container sour cream", false, 1),
		(234, "quinoa", false, 1),
		(235, "vegetable broth", false, 1),
		(236, "frozen corn kernels", false, 1),
		(237, "cans black beans", false, 1),
		(238, "ground beef", false, 2),
		(239, "dried bread crumbs", false, 1),
		(240, "prepared mustard", false, 1),
		(241, "raspberries", false, 1),
		(242, "strawberries", false, 2),
		(243, "fruit preserves", false, 1),
		(244, "inch) flour tortillas", false, 3),
		(245, "cinnamon sugar", false, 1),
		(246, "chopped green onions", false, 1),
		(247, "can diced green chiles", false, 1),
		(248, "cubed cooked chicken breast meat", false, 1),
		(249, "pork tenderloin", false, 2),
		(250, "can or bottle root beer", false, 1),
		(251, "bottle your favorite barbecue sauce", false, 1),
		(252, "sifted confectioners' sugar", false, 1),
		(253, "butter flavored shortening", false, 1),
		(254, "rolled oats", false, 1),
		(255, "garlic salt", false, 1),
		(256, "salmon", false, 2),
		(257, "inch cubes", false, 3),
		(258, "beef broth", false, 1),
		(259, "stalk celery", false, 3),
		(260, "pinch salt", false, 3),
		(261, "thick slices bread", false, 3),
		(262, "cubed beef stew meat", false, 2),
		(263, "can condensed golden mushroom soup", false, 1),
		(264, "quick cooking oats", false, 1),
		(265, "white pepper", false, 1),
		(266, "whole chickens", false, 2),
		(267, "can condensed French onion soup", false, 1),
		(268, "dry bread crumbs", false, 1),
		(269, "mustard powder", false, 1),
		(270, "can diced tomatoes", false, 1),
		(271, "balsamic vinegar", false, 1),
		(272, "dried rosemary", false, 1),
		(273, "almonds", false, 1),
		(274, "spinach", false, 2),
		(275, "dried cranberries", false, 1),
		(276, "toasted sesame seeds", false, 1),
		(277, "poppy seeds", false, 1),
		(278, "white wine vinegar", false, 1),
		(279, "whole fresh mushrooms", false, 3),
		(280, "ground cayenne pepper", false, 1),
		(281, "ranch dressing", false, 1),
		(282, "minced fresh rosemary", false, 1),
		(283, "lemon juice", false, 1),
		(284, "package dry Italian-style salad dressing mix", false, 1),
		(285, "can condensed cream of chicken soup", false, 1),
		(286, "rump roast", false, 2),
		(287, "can beef broth", false, 1),
		(288, "peanut butter", false, 1),
		(289, "canned pumpkin puree", false, 1),
		(290, "melted butter", false, 1),
		(291, "can black olives", false, 1),
		(292, "can diced green chili peppers", false, 1),
		(293, "can diced tomatoes with green chile peppers", false, 1),
		(294, "jar taco sauce", false, 1),
		(295, "cans refried beans", false, 1),
		(296, " flour tortillas", false, 3),
		(297, "shredded Colby cheese", false, 1),
		(298, "chopped fresh ginger root", false, 1),
		(299, "chopped garlic", false, 1),
		(300, "hot sauce", false, 1),
		(301, "inch strips", false, 3),
		(302, "cream cheese with chives", false, 1),
		(303, "angel hair pasta", false, 2),
		(304, "can chopped green chilies", false, 1),
		(305, "canned diced jalapeno peppers", false, 1),
		(306, "cocoa powder", false, 1),
		(307, "package bow tie pasta", false, 1),
		(308, "red pepper flakes", false, 1),
		(309, "can Italian-style plum tomatoes", false, 1),
		(310, "heavy cream", false, 1),
		(311, "minced fresh parsley", false, 1),
		(312, "Brussels sprouts", false, 2),
		(313, "kosher salt", false, 1),
		(314, "freshly ground black pepper", false, 1),
		(315, "freshly grated Parmesan cheese", false, 1),
		(316, "chicken wings", false, 3),
		(317, "dash ground black pepper", false, 3),
		(318, "dash garlic powder", false, 3),
		(319, "light corn syrup", false, 1),
		(320, "almond extract", false, 1),
		(321, "extra lean ground beef", false, 2),
		(322, "dash hot pepper sauce ", false, 3),
		(323, "skim milk", false, 1),
		(324, "seasoned bread crumbs", false, 1),
		(325, " prepared graham cracker crust", false, 3),
		(326, "pumpkin puree", false, 1),
		(327, "pinch ground cloves", false, 3),
		(328, "frozen whipped topping", false, 1);
