http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  userApi:
    host: 'localhost'
    paths: 
      - '/user/*'
      - '/user'
  suggestionApi:
    host: 'localhost'
    paths: 
      - '/suggestion/*'
      - '/suggestion'
serviceEndpoints:
  userService:
    url: "http://localhost:${USER_PORT:-8000}"
  suggestionService:
    url: "http://localhost:8585"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: user
    apiEndpoints:
      - userApi
    policies:
      - proxy:
        - action:
            serviceEndpoint: userService
            changeOrigin: true
  - name: suggestion
    apiEndpoints:
      - suggestionApi
    policies:
      - proxy:
        - action:
            serviceEndpoint: suggestionService
            changeOrigin: true